---
- name: Commenting
  hosts: test
  gather_facts: no
  become: true
  tasks:
   
          #- name: extacting ID's
      #shell: cat /root/Hemanth/resigned  
      #register: output
      #delegate_to: localhost

    - name: delete the line
      lineinfile:
        path: /root/Hemanth/edetails
        regexp: '#'
        state: absent
        #loop: "{{ output.stdout_lines }}"
