---
- name: Configure Router External Gateway
  hosts: localhost
  gather_facts: false
  vars:
    router: "{{ router }}"
    
  tasks:

    - name: Configure external gateway
      openstack.cloud.router:
        state: present
        name: "{{ router }}"
        external_gateway_info:
          network: public
      register: router_gateway

    - name: Display result
      debug:
        var: router_gateway
