---
- name: Manage OpenStack Network
  hosts: localhost
  gather_facts: false
  vars:
    network: "{{ network }}"
  tasks:
    - name: Create/Delete Network
      openstack.cloud.network:
        state: present
        name: "{{ network }}"
        shared: false
        external: false
      register: network

    - name: Display Result
      debug:
        var: network
